project:
  type: book
  output-dir: ../output

book:
  title: "Assessing a Formal Model of Reflective Equilibrium"
  subtitle: "Technical Report"
  description: "Based on Beisbart, Betz, and Brun (2021), this report assesses different models of reflective equilibrium (RE) by numerical investigation."
  author: 
    - name: Andreas Freivogel
      affiliation: 
      - name: University of Bern
        url: https://www.unibe.ch/eng/
    - name: Sebastian Cacean
      affiliation: 
      - name: Karlsruhe Institute of Technology (KIT)
        url: https://www.kit.edu/
  date: March 01, 2024
  downloads: [pdf]
  sharing: [twitter, linkedin]
  site-url: https://re-models.github.io/re-technical-report/
  repo-url: https://github.com/re-models/re-technical-report
  license: "CC BY"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_general-props.qmd
    - chapter_go-and-fp.qmd
    - chapter_full-re-states.qmd
    - chapter_commitment-consistency.qmd
    - chapter_extreme-values.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - appendix_tipping_line.qmd
    - appendix_trivial_endpoints.qmd
    - appendix_systematicity.qmd
  keyword: "philosophy, formal-methods, modelling, epistemology, reflective-equilibrium"

citation: 
  type: report
  url: https://re-models.github.io/re-technical-report/
  doi: 10.5555/12345678



google-scholar: true

bibliography: references.bib


format:
  html:
    theme: cosmo
    toc-depth: 4
  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex

tbl-cap-location: bottom


