project:
  type: book
  output-dir: ../output

book:
  title: "Assessing a Formal Model of Reflective Equilibrium"
  subtitle: "Technical Report"
  author: "Andreas Freivogel, Sebastian Cacean"
  date: December 31, 2023
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_general-props.qmd
    - chapter_go-and-fp.qmd
    - chapter_full-re-states.qmd
    - chapter_commitment-consistency.qmd
    - chapter_extreme-values.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - appendix_tipping_line.qmd
    - appendix_trivial_endpoints.qmd
    - appendix_systematicity.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 4
  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex

tbl-cap-location: bottom


