project:
  type: book
  output-dir: ../docs

book:
  title: "Assessing a Formal Model of Reflective Equilibrium"
  subtitle: "Technical Report (v1.0)"
  description: "In philosophy, and especially in ethics, reflective equilibrium (RE) is often considered a powerful method for obtaining beliefs that mutually support each other, are justified by evidence, and are backed by good reasons. Based on Beisbart, Betz, and Brun (2021), this report assesses formal RE models by numerical investigation to scrutinize and advance the method."
  author: 
    - name: Andreas Freivogel
      affiliation: 
      - name: University of Bern
        url: https://www.unibe.ch/eng/
    - name: Sebastian Cacean
      affiliation: 
      - name: Karlsruhe Institute of Technology (KIT)
        url: https://www.kit.edu/
  date: August 11, 2024
  version: v1.0
  doi: 10.5281/zenodo.13294165
  downloads: [pdf]
  sharing: [twitter, linkedin]
  site-url: https://re-models.github.io/re-technical-report/
  repo-url: https://github.com/re-models/re-technical-report
  license: "CC BY"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_general-props.qmd
    - chapter_go-and-fp.qmd
    - chapter_full-re-states.qmd
    - chapter_commitment-consistency.qmd
    - chapter_extreme-values.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - appendix_tipping_line.qmd
    - appendix_trivial_endpoints.qmd
    - appendix_systematicity.qmd
  keyword: "philosophy, formal-methods, modelling, epistemology, reflective-equilibrium"

citation: 
  type: report
  url: https://re-models.github.io/re-technical-report/
  doi: 10.5555/12345678



google-scholar: true

bibliography: references.bib


format:
  html:
    theme: cosmo
    toc-depth: 4
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex
    

tbl-cap-location: bottom


