project:
  type: book
  output-dir: ../output

book:
  title: "Technical Report"
  subtitle: "Assessing a Formal Model of Reflective Equilibrium"
  author: "Andreas Freivogel, Sebastian Cacean"
  date: December 31, 2023
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_go-and-fp.qmd
    - chapter_full-re-states.qmd
    - chapter_commitment-consistenc.qmd
    - chapter_extreme-values.qmd
    - chapter_sec-general-props.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



